### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by pchulpjoost**
Removed the base64 ascci art so it can be run on the SonicPad

### CODE REVIEW

**Comment by crysxd** [comment]
Thanks for the PR! I think it's better to make the ASCII art optional by appending `| true` so if `base64` fails the script continues. I like my ASCII art :)

Did you encounter any other issues with the Sonic Pad besides this? I don't have one myself unfortunately.

**Comment by pchulpjoost** [comment]
Hi Christian,

Tanks for your reply. The script did run after I removed your beautiful art.
Unfortunately, the Octo Everywhere App still says that the companion plug-in isn’t installed.
I haven’t had the time to look into it further.

If you find it interesting to play with the SonicPad, I can give you remote access to it and you can see for yourself.

Kind regards, Met vriendelijke groet,

**Comment by crysxd** [comment]
That would be awesome! Some time ago somebody also mentioned that there are problems with the installation because of a specific python package I use, but that doesn't seem to be the problem for you.

Could you start by sending me a bug report from the app? You can do so at main menu > Settings > FAQ & Help > Report a bug. This most likely will already tell me what the problem is with the notifications :)

**Comment by pchulpjoost** [comment]
Hi Christian,

here you go!

Feedback OctoApp for iPadOS 2.0.25

**Comment by crysxd** [comment]
Please send it to the prefilled email address hello@octoapp.eu! GitHub didn't pick up the attachment and I also wouldn't recommend posting the debug bundle publicly.

**Comment by crysxd** [comment]
Errors in base64 are now ignored, on Sonic Pad it will just ignore the command and move on :)
I'm waiting for your bug report! :)

**Comment by pchulpjoost** [comment]
Great! I've send the e-mail.

Met vriendelijke groeten,

Joost Blankestijn
0612326034
blankestijnict.nl
________________________________
Van: Christian Würthner ***@***.***>
Verzonden: zondag 18 februari 2024 07:21
Aan: crysxd/OctoApp-Plugin ***@***.***>
CC: pchulpjoost ***@***.***>; Author ***@***.***>
Onderwerp: Re: [crysxd/OctoApp-Plugin] Update install.sh (PR #54)


Errors in base64 are now ignored, on Sonic Pad it will just ignore the command and move on :)
I'm waiting for your bug report! :)

**Pull request merged**
